name: Publish Library

on:
  release:
    types: [published]

env:
  PACKAGE_TOKEN: ${{secrets.GIT_TOKEN}}

permissions:
  contents: read
  packages: write

jobs:
  publish_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Token
        run: echo "Token is $PACKAGE_TOKEN"
      - name: Build Library
        run: sbt publish