name: Publish Library

on:
  release:
    types: [published]

env:
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

permissions:
  contents: read
  packages: write

jobs:
  publish_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:1})
      - name: Build Library
        run: sbt publish